#ifndef __KEYBOARD_KEYS__
#define __KEYBOARD_KEYS__

enum KEYPRESS_EVENT {
     KEYPRESS_NONE,
     KEYPRESS_SELECT,
     KEYPRESS_LEFT,
     KEYPRESS_UP,
     KEYPRESS_DOWN,
     KEYPRESS_RIGHT
};

#endif
